### ISSUE TITLE
Cannot read properties of undefined (reading 'roles') (Vote)

### ISSUE THREAD

**Issue by arceusxx** [ishaantek/UniverseList#92]
```
TypeError: /home/container/src/pages/botlist/viewbot.ejs:65
    63|               <a href="/bots/<%= bot.id %>/review" type="button" style="border-radius: 5px;" class="btn btn-info pr-3 pl-3 mr-1"><i class="fa-solid fa-pen-to-square"></i> Review</a>
    64|               <% } %>
 >> 65|           <% if (bot.owner.includes(user.id) || member.roles.cache.some((role) => role.id === config.roles.bottester)) { %>
    66|           <a href="/bots/<%= bot.id %>/edit" type="button" style="border-radius: 5px;" class="btn btn-warning pr-3 pl-3 mr-1"><i class="fa-solid fa-pen-to-square"></i> Edit</a>
    67|           <% } %>
    68|           <% if (bot.owner.includes(user.id)) { %>
Cannot read properties of undefined (reading 'roles')
    at eval ("/home/container/src/pages/botlist/viewbot.ejs":127:50)
    at viewbot (/home/container/node_modules/ejs/lib/ejs.js:703:17)
    at tryHandleCache (/home/container/node_modules/ejs/lib/ejs.js:274:36)
    at exports.renderFile [as engine] (/home/container/node_modules/ejs/lib/ejs.js:491:10)
    at View.render (/home/container/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/container/node_modules/express/lib/application.js:657:10)
    at Function.render (/home/container/node_modules/express/lib/application.js:609:3)
    at ServerResponse.render (/home/container/node_modules/express/lib/response.js:1039:7)
    at res.render (/home/container/node_modules/express-minify-html-terser/minifier.js:82:16)
    at /home/container/src/app.js:969:7
```

![image](https://github.com/ishaantek/UniverseList/assets/96443442/519d0c3e-a6ec-4ce8-aee5-7b788c6aa8d5)
it happens when someone votes for a bot.

**Comment by AviDevs** [comment]
Que mal que salio eso iba a probar

**Comment by arceusxx** [comment]
since there's been no response, i assume there are no plans to resolve this error. however, if that's the case, we'll reopen issue #92.

**Comment by ishaantek** [comment]
Hello,

Thank you for bringing this issue to our attention. Upon reviewing the error message you provided, it seems that the problem occurs when a user is logged in to the website but has not joined the corresponding Discord server. This issue arises because the website relies on accessing the roles of the user, which is not possible when the user is not in the Discord server.

Since the website cannot retrieve the roles of users who have not joined the server, it leads to the error you encountered. To resolve this, users need to join the Discord server associated with the website to ensure the website can access their roles and prevent any further errors.

Please let us know if you have any further questions or require additional assistance.

**Comment by arceusxx** [comment]
this means that all users who want to vote for a bot must be present on the Discord server to avoid this error...

**Comment by ishaantek** [comment]
Indeed, you are correct. To avoid the error you encountered, users who wish to vote for a bot must be present on the Discord server associated with the website. The website relies on checking the roles of users to determine if they are the bot developer (allowing access to developer tools) or if they are admin (allowing access to admin tools).

When a user is not present on the server, the website cannot verify their roles, resulting in the error you experienced. Therefore, it is necessary for users to join the Discord server so that the website can successfully check their roles and provide the appropriate access and functionality.

If you have any further questions or need additional clarification, please feel free to ask.

**Comment by arceusxx** [comment]
resolved in that case
